hpge_icpc_bulk_2vbb:
  template: $_/templates/default.mac
  generator: ~defines:2vbb
  confinement: ~volumes.bulk:^[V].*
  primaries_per_job: 35000000
  number_of_jobs: 1

hpge_icpc_bulk_0vbb:
  template: $_/templates/default.mac
  generator: ~defines:0vbb
  confinement: ~volumes.bulk:^[V].*
  primaries_per_job: 15000000
  number_of_jobs: 1

hpge_ppc_bulk_2vbb:
  template: $_/templates/default.mac
  generator: ~defines:2vbb
  confinement: ~volumes.bulk:^[P].*
  primaries_per_job: 30000000
  number_of_jobs: 1

hpge_ppc_bulk_0vbb:
  template: $_/templates/default.mac
  generator: ~defines:0vbb
  confinement: ~volumes.bulk:^[P].*
  primaries_per_job: 15000000
  number_of_jobs: 1

hpge_coax_bulk_2vbb:
  template: $_/templates/default.mac
  generator: ~defines:2vbb
  confinement: ~volumes.bulk:^[C].*
  primaries_per_job: 35000000
  number_of_jobs: 1

hpge_coax_bulk_0vbb:
  template: $_/templates/default.mac
  generator: ~defines:0vbb
  confinement: ~volumes.bulk:^[C].*
  primaries_per_job: 20000000
  number_of_jobs: 1

hpge_bege_bulk_2vbb:
  template: $_/templates/default.mac
  generator: ~defines:2vbb
  confinement: ~volumes.bulk:^[B].*
  primaries_per_job: 35000000
  number_of_jobs: 1

hpge_bege_bulk_0vbb:
  template: $_/templates/default.mac
  generator: ~defines:0vbb
  confinement: ~volumes.bulk:^[B].*
  primaries_per_job: 20000000
  number_of_jobs: 1

birds_nest_Pb212_to_Pb208: &Th228
  template: $_/templates/default.mac
  generator: ~defines:Pb212_to_Pb208
  confinement: ~volumes.bulk:birds_nest_plate_copper
  primaries_per_job: 1500000
  number_of_jobs: 20

hpge_support_copper_Pb212_to_Pb208:
  <<: *Th228
  confinement: ~volumes.bulk:hpge_string_support_.*_copper_.*
  primaries_per_job: 1500000
  number_of_jobs: 7

ultem_insulators_Pb212_to_Pb208:
  <<: *Th228
  confinement: ~volumes.bulk:hpge_assembly_insulator_ultem_.*
  primaries_per_job: 2000000
  number_of_jobs: 5

front_end_electronics_Pb212_to_Pb208:
  <<: *Th228
  confinement: ~volumes.bulk:hpge_assembly_lmfe_.*
  primaries_per_job: 400000
  number_of_jobs: 25

cables_Pb212_to_Pb208:
  <<: *Th228
  confinement: ~volumes.bulk:hpge_cable_.*
  primaries_per_job: 650000
  number_of_jobs: 16

pen_plates_Pb212_to_Pb208:
  <<: *Th228
  confinement: ~volumes.bulk:hpge_assembly_.*_pen.*
  primaries_per_job: 1500000
  number_of_jobs: 7

sipm_arrays_Pb212_to_Pb208:
  <<: *Th228
  confinement: ~volumes.bulk:S.*
  primaries_per_job: 3000000
  number_of_jobs: 10

wls_reflector_Pb212_to_Pb208:
  <<: *Th228
  confinement: ~volumes.bulk:wlsr_.*
  primaries_per_job: 5000000
  number_of_jobs: 15

minishrouds_Pb212_to_Pb208:
  <<: *Th228
  confinement: ~volumes.bulk:minishroud_.*
  primaries_per_job: 2500000
  number_of_jobs: 4

fibers_Pb212_to_Pb208:
  <<: *Th228
  confinement: ~volumes.bulk:fiber_.*
  primaries_per_job: 1500000
  number_of_jobs: 7

fiber_support_copper_Pb212_to_Pb208:
  <<: *Th228
  confinement: ~volumes.bulk:larinstr_support_.*
  primaries_per_job: 4500000
  number_of_jobs: 3

birds_nest_K40: &K40
  template: $_/templates/default.mac
  generator: ~defines:K40
  confinement: ~volumes.bulk:birds_nest_plate_copper
  primaries_per_job: 6500000
  number_of_jobs: 10

hpge_support_copper_K40:
  <<: *K40
  confinement: ~volumes.bulk:hpge_string_support_.*_copper_.*
  primaries_per_job: 5500000
  number_of_jobs: 2

ultem_insulators_K40:
  <<: *K40
  confinement: ~volumes.bulk:hpge_assembly_insulator_ultem_.*
  primaries_per_job: 4000000
  number_of_jobs: 3

front_end_electronics_K40:
  <<: *K40
  confinement: ~volumes.bulk:hpge_assembly_lmfe_.*
  primaries_per_job: 600000
  number_of_jobs: 17

cables_K40:
  <<: *K40
  confinement: ~volumes.bulk:hpge_cable_.*
  primaries_per_job: 900000
  number_of_jobs: 12

pen_plates_K40:
  <<: *K40
  confinement: ~volumes.bulk:hpge_assembly_.*_pen.*
  primaries_per_job: 2500000
  number_of_jobs: 4

sipm_arrays_K40:
  <<: *K40
  confinement: ~volumes.bulk:S.*
  primaries_per_job: 8500000
  number_of_jobs: 5

wls_reflector_K40:
  <<: *K40
  confinement: ~volumes.bulk:wlsr_.*
  primaries_per_job: 15000000
  number_of_jobs: 10

minishrouds_K40:
  <<: *K40
  confinement: ~volumes.bulk:minishroud_.*
  primaries_per_job: 5500000
  number_of_jobs: 2

fibers_K40:
  <<: *K40
  confinement: ~volumes.bulk:fiber_.*
  primaries_per_job: 1500000
  number_of_jobs: 7

fiber_support_copper_K40:
  <<: *K40
  confinement: ~volumes.bulk:larinstr_support_.*
  primaries_per_job: 20000000
  number_of_jobs: 1

birds_nest_Ra228_to_Ac228: &Ac228
  template: $_/templates/default.mac
  generator: ~defines:Ra228_to_Ac228
  confinement: ~volumes.bulk:birds_nest_plate_copper
  primaries_per_job: 2000000
  number_of_jobs: 20

hpge_support_copper_Ra228_to_Ac228:
  <<: *Ac228
  confinement: ~volumes.bulk:hpge_string_support_.*_copper_.*
  primaries_per_job: 2000000
  number_of_jobs: 5

ultem_insulators_Ra228_to_Ac228:
  <<: *Ac228
  confinement: ~volumes.bulk:hpge_assembly_insulator_ultem_.*
  primaries_per_job: 2500000
  number_of_jobs: 4

front_end_electronics_Ra228_to_Ac228:
  <<: *Ac228
  confinement: ~volumes.bulk:hpge_assembly_lmfe_.*
  primaries_per_job: 750000
  number_of_jobs: 14

cables_Ra228_to_Ac228:
  <<: *Ac228
  confinement: ~volumes.bulk:hpge_cable_.*
  primaries_per_job: 1000000
  number_of_jobs: 10

pen_plates_Ra228_to_Ac228:
  <<: *Ac228
  confinement: ~volumes.bulk:hpge_assembly_.*_pen.*
  primaries_per_job: 2000000
  number_of_jobs: 5

sipm_arrays_Ra228_to_Ac228:
  <<: *Ac228
  confinement: ~volumes.bulk:S.*
  primaries_per_job: 3500000
  number_of_jobs: 5

wls_reflector_Ra228_to_Ac228:
  <<: *Ac228
  confinement: ~volumes.bulk:wlsr_.*
  primaries_per_job: 6000000
  number_of_jobs: 15

minishrouds_Ra228_to_Ac228:
  <<: *Ac228
  confinement: ~volumes.bulk:minishroud_.*
  primaries_per_job: 3000000
  number_of_jobs: 4

fibers_Ra228_to_Ac228:
  <<: *Ac228
  confinement: ~volumes.bulk:fiber_.*
  primaries_per_job: 1500000
  number_of_jobs: 7

fiber_support_copper_Ra228_to_Ac228:
  <<: *Ac228
  confinement: ~volumes.bulk:larinstr_support_.*
  primaries_per_job: 5500000
  number_of_jobs: 2

birds_nest_Pb214_to_Po214: &U238
  template: $_/templates/default.mac
  generator: ~defines:Pb214_to_Po214
  confinement: ~volumes.bulk:birds_nest_plate_copper
  primaries_per_job: 1500000
  number_of_jobs: 20

hpge_support_copper_Pb214_to_Po214:
  <<: *U238
  confinement: ~volumes.bulk:hpge_string_support_.*_copper_.*
  primaries_per_job: 1000000
  number_of_jobs: 10

ultem_insulators_Pb214_to_Po214:
  <<: *U238
  confinement: ~volumes.bulk:hpge_assembly_insulator_ultem_.*
  primaries_per_job: 1500000
  number_of_jobs: 7

front_end_electronics_Pb214_to_Po214:
  <<: *U238
  confinement: ~volumes.bulk:hpge_assembly_lmfe_.*
  primaries_per_job: 350000
  number_of_jobs: 29

cables_Pb214_to_Po214:
  <<: *U238
  confinement: ~volumes.bulk:hpge_cable_.*
  primaries_per_job: 550000
  number_of_jobs: 19

pen_plates_Pb214_to_Po214:
  <<: *U238
  confinement: ~volumes.bulk:hpge_assembly_.*_pen.*
  primaries_per_job: 1000000
  number_of_jobs: 10

sipm_arrays_Pb214_to_Po214:
  <<: *U238
  confinement: ~volumes.bulk:S.*
  primaries_per_job: 2000000
  number_of_jobs: 10

wls_reflector_Pb214_to_Po214:
  <<: *U238
  confinement: ~volumes.bulk:wlsr_.*
  primaries_per_job: 4000000
  number_of_jobs: 20

minishrouds_Pb214_to_Po214:
  <<: *U238
  confinement: ~volumes.bulk:minishroud_.*
  primaries_per_job: 2000000
  number_of_jobs: 5

fibers_Pb214_to_Po214:
  <<: *U238
  confinement: ~volumes.bulk:fiber_.*
  primaries_per_job: 1500000
  number_of_jobs: 7

fiber_support_copper_Pb214_to_Po214:
  <<: *U238
  confinement: ~volumes.bulk:larinstr_support_.*
  primaries_per_job: 3500000
  number_of_jobs: 3

hpge_bege_nplus_surface_K42: &K42
  generator: ~defines:K42
  template: $_/templates/step_limits.mac
  confinement: ~vertices:hpge_bege_nplus_surface
  macro_substitutions:
    STEP_SIZE: 20 um
  primaries_per_job: 2000000
  number_of_jobs: 5

hpge_ic_nplus_surface_K42:
  <<: *K42
  confinement: ~vertices:hpge_ic_nplus_surface
  primaries_per_job: 2000000
  number_of_jobs: 5

hpge_ppc_nplus_surface_K42:
  <<: *K42
  confinement: ~vertices:hpge_ppc_nplus_surface
  primaries_per_job: 950000
  number_of_jobs: 11

hpge_coax_nplus_surface_K42:
  <<: *K42
  confinement: ~vertices:hpge_coax_nplus_surface
  primaries_per_job: 950000
  number_of_jobs: 11

hpge_bege_pplus_surface_K42:
  <<: *K42
  confinement: ~vertices:hpge_bege_pplus_surface
  primaries_per_job: 1000000
  number_of_jobs: 10

hpge_ic_pplus_surface_K42:
  <<: *K42
  confinement: ~vertices:hpge_ic_pplus_surface
  primaries_per_job: 1000000
  number_of_jobs: 10

hpge_ppc_pplus_surface_K42:
  <<: *K42
  confinement: ~vertices:hpge_ppc_pplus_surface
  primaries_per_job: 2500000
  number_of_jobs: 4

hpge_coax_pplus_surface_K42:
  <<: *K42
  confinement: ~vertices:hpge_coax_pplus_surface
  primaries_per_job: 2500000
  number_of_jobs: 4

hpge_support_copper_Co60:
  template: $_/templates/default.mac
  generator: ~defines:Co60
  confinement: ~volumes.bulk:hpge_string_support_.*_copper_.*
  primaries_per_job: 1500000
  number_of_jobs: 7

hpge_support_copper_Mn54:
  template: $_/templates/default.mac
  generator: ~defines:Mn54
  confinement: ~volumes.bulk:hpge_string_support_.*_copper_.*
  primaries_per_job: 3000000
  number_of_jobs: 4

liquid_argon_outside_minishroud_K42:
  template: $_/templates/default.mac
  generator: ~defines:K42
  confinement: >-
    ~function:legendsimflow.confine.get_lar_minishroud_confine_commands(
      <...>,
      'minishroud_tube*',
      False,
      lar_name='liquid_argon',
      outer_radius_in_mm=1000,
      outer_height_in_mm=3000
    )
  primaries_per_job: 7500000
  number_of_jobs: 10

liquid_argon_inside_minishroud_K42:
  template: $_/templates/default.mac
  generator: ~defines:K42
  confinement: >-
    ~function:legendsimflow.confine.get_lar_minishroud_confine_commands(
      <...>,
      'minishroud_tube*',
      True,
      lar_name='liquid_argon'
    )
  primaries_per_job: 2000000
  number_of_jobs: 10
fiber_support_copper_surface_K42:
  template: $_/templates/default.mac
  generator: ~defines:K42
  confinement: ~volumes.surface:larinstr_support_.*
  primaries_per_job: 5000000
  number_of_jobs: 20

liquid_argon_Ar39:
  template: $_/templates/default.mac
  generator: ~defines:Ar39
  confinement: ~defines:lar_inside_wlsr
  primaries_per_job: 35000000
  number_of_jobs: 10
