l200a-birds-nest-K40:
  template: template.mac
  generator: K40
  confinement: birds-nest
  number_of_primaries: 500000000
  number_of_jobs: 500

l200a-birds-nest-Ra224-to-Pb208:
  template: template.mac
  generator: Ra224-to-Pb208
  confinement: birds-nest
  number_of_primaries: 200000000
  number_of_jobs: 2500

l200a-birds-nest-Rn222-to-Po214:
  template: template.mac
  generator: Rn222-to-Po214
  confinement: birds-nest
  number_of_primaries: 200000000
  number_of_jobs: 3200

l200a-birds-nest-Ra228-to-Ac228:
  template: template.mac
  generator: Ra228-to-Ac228
  confinement: birds-nest
  number_of_primaries: 200000000
  number_of_jobs: 1600

l200a-fiber-support-copper-Co60:
  template: template.mac
  generator: Co60
  confinement: fiber-support-copper
  number_of_primaries: 100000000
  number_of_jobs: 1250

l200a-fiber-support-copper-K40:
  template: template.mac
  generator: K40
  confinement: fiber-support-copper
  number_of_primaries: 100000000
  number_of_jobs: 640

l200a-fiber-support-copper-Ra224-to-Pb208:
  template: template.mac
  generator: Ra224-to-Pb208
  confinement: fiber-support-copper
  number_of_primaries: 100000000
  number_of_jobs: 1250

l200a-fiber-support-copper-Rn222-to-Po214:
  template: template.mac
  generator: Rn222-to-Po214
  confinement: fiber-support-copper
  number_of_primaries: 100000000
  number_of_jobs: 1250

l200a-fiber-support-copper-Ra228-to-Ac228:
  template: template.mac
  generator: Ra228-to-Ac228
  confinement: fiber-support-copper
  number_of_primaries: 100000000
  number_of_jobs: 1000

l200a-fiber-inner-support-copper-Ra224-to-Pb208:
  template: template.mac
  generator: Ra228-to-Ac228
  confinement: fiber-inner-support-copper
  number_of_primaries: 100000000
  number_of_jobs: 1000

l200a-fiber-inner-support-copper-Rn222-to-Po214:
  template: template.mac
  confinement: fiber-inner-support-copper
  generator: Rn222-to-Po214
  number_of_primaries: 100000000
  number_of_jobs: 1000

l200a-fiber-outer-support-copper-Ra224-to-Pb208:
  template: template.mac
  generator: Ra224-to-Pb208
  confinement: fiber-outer-support-copper
  number_of_primaries: 100000000
  number_of_jobs: 1000

l200a-fiber-outer-support-copper-Rn222-to-Po214:
  template: template.mac
  generator: Rn2222-to-Po214
  confinement: fiber-outer-support-copper
  number_of_primaries: 100000000
  number_of_jobs: 1000

l200a-fibers-K40:
  template: template.mac
  generator: K40
  confinement: fibers
  number_of_primaries: 100000000
  number_of_jobs: 100

l200a-fibers-Ra224-to-Pb208:
  template: template.mac
  generator: Ra224-to-Pb208
  confinement: fibers
  number_of_primaries: 100000000
  number_of_jobs: 640

l200a-fibers-Rn222-to-Po214:
  template: template.mac
  generator: Rn222-to-Pb214
  confinement: fibers
  number_of_primaries: 100000000
  number_of_jobs: 640

l200a-fibers-Ra228-to-Ac228:
  template: template.mac
  generator: Ra228-to-Ac228
  confinement: fibers
  number_of_primaries: 100000000
  number_of_jobs: 500

l200a-fibers-inner-Ra224-to-Pb208:
  template: template.mac
  generator: Ra224-to-Pb208
  confinement: fibers-inner
  number_of_primaries: 100000000
  number_of_jobs: 500

l200a-fibers-inner-Rn222-to-Po214:
  template: template.mac
  generator: Rn222-to-Po214
  confinement: fibers-inner
  number_of_primaries: 100000000
  number_of_jobs: 500

l200a-fibers-outer-Ra224-to-Pb208:
  template: template.mac
  generator: Ra224-to-Pb208
  confinement: fibers-outer
  number_of_primaries: 100000000
  number_of_jobs: 500

l200a-fibers-inner-Ra228-to-Ac228:
  template: template.mac
  generator: Ra228-to-Ac228
  confinement: fibers-outer
  number_of_primaries: 100000000
  number_of_jobs: 500

l200a-fibers-inner-K40:
  template: template.mac
  generator: K40
  confinement: fibers-inner
  number_of_primaries: 100000000
  number_of_jobs: 100

l200a-fibers-outer-Rn222-to-Po214:
  template: template.mac
  generator: Rn222-to-Po214
  confinement: fibers-outer
  number_of_primaries: 100000000
  number_of_jobs: 500

l200a-front-end-electronics-Co60:
  template: template.mac
  generator: Co60
  confinement: front-end-electronics
  number_of_primaries: 100000000
  number_of_jobs: 250

l200a-front-end-electronics-K40:
  template: template.mac
  generator: K40
  confinement: front-end-electronics
  number_of_primaries: 100000000
  number_of_jobs: 100

l200a-front-end-electronics-Ra224-to-Pb208:
  template: template.mac
  generator: Ra224-to-Pb208
  confinement: front-end-electronics
  number_of_primaries: 100000000
  number_of_jobs: 250

l200a-front-end-electronics-Rn222-to-Po214:
  template: template.mac
  generator: Rn222-to-Po214
  confinement: front-end-electronics
  number_of_primaries: 100000000
  number_of_jobs: 250

l200a-front-end-electronics-Ra228-to-Ac228:
  template: template.mac
  generator: Ra228-to-Ac228
  confinement: front-end-electronics
  number_of_primaries: 100000000
  number_of_jobs: 125

l200a-hpge-bulk-2vbb:
  template: template.mac
  generator: 2vbb
  confinement: hpge-bulk
  number_of_primaries: 100000000
  number_of_jobs: 100

l200a-hpge-bulk-0vbb:
  template: template.mac
  generator: 0vbb
  confinement: hpge-bulk
  number_of_primaries: 100000000
  number_of_jobs: 100

l200a-hpge-insulators-K40:
  template: template.mac
  generator: K40
  confinement: hpge-insulators
  number_of_primaries: 100000000
  number_of_jobs: 50

l200a-hpge-insulators-Ra224-to-Pb208:
  template: template.mac
  generator: Ra224-to-Pb208
  confinement: hpge-insulators
  number_of_primaries: 100000000
  number_of_jobs: 320

l200a-hpge-insulators-Rn222-to-Po214:
  template: template.mac
  generator: Rn222-to-Po214
  confinement: hpge-insulators
  number_of_primaries: 100000000
  number_of_jobs: 400

l200a-hpge-insulators-Ra228-to-Ac228:
  template: template.mac
  generator: Ra228-to-Ac228
  confinement: hpge-insulators
  number_of_primaries: 100000000
  number_of_jobs: 200

l200a-hpge-support-copper-Co60:
  template: template.mac
  generator: Co60
  confinement: hpge-support-copper
  number_of_primaries: 100000000
  number_of_jobs: 250

l200a-hpge-support-copper-K40:
  template: template.mac
  generator: K40
  confinement: hpge-support-copper
  number_of_primaries: 100000000
  number_of_jobs: 100

l200a-hpge-support-copper-Ra224-to-Pb208:
  template: template.mac
  generator: Ra224-to-Pb208
  confinement: hpge-support-copper
  number_of_primaries: 100000000
  number_of_jobs: 250

l200a-hpge-support-copper-Rn222-to-Po214:
  template: template.mac
  generator: Rn222-to-Po214
  confinement: hpge-support-copper
  number_of_primaries: 100000000
  number_of_jobs: 400

l200a-hpge-support-copper-Ra228-to-Ac228:
  template: template.mac
  generator: Ra228-to-Ac228
  confinement: hpge-support-copper
  number_of_primaries: 100000000
  number_of_jobs: 200

l200a-hpge-support-copper-Mn54:
  template: template.mac
  generator: Mn54
  confinement: hpge-support-copper
  number_of_primaries: 100000000
  number_of_jobs: 100

l200a-hpge-surface-K42:
  template: template.mac
  generator: K42
  confinement: hpge-surface
  number_of_primaries: 10000000
  vertices: l200a-hpge-surface-vertices

l200a-hpge-surface-Ra224-to-Pb208:
  template: template.mac
  generator: Ra224-to-Pb208
  confinement: hpge-surface
  number_of_primaries: 10000000
  vertices: l200a-hpge-surface-vertices

l200a-hv-signal-cables-Co60:
  template: template.mac
  generator: Co60
  confinement: hv-signal-cables
  number_of_primaries: 100000000
  number_of_jobs: 3200

l200a-hv-signal-cables-K40:
  template: template.mac
  generator: K40
  confinement: hv-signal-cables
  number_of_primaries: 100000000
  number_of_jobs: 250

l200a-hv-signal-cables-Ra224-to-Pb208:
  template: template.mac
  generator: Ra224-to-Pb208
  confinement: hv-signal-cables
  number_of_primaries: 100000000
  number_of_jobs: 2500

l200a-hv-signal-cables-Rn222-to-Pb214:
  template: template.mac
  generator: Rn222-to-Pb214
  confinement: hv-signal-cables
  number_of_primaries: 100000000
  number_of_jobs: 2500

l200a-hv-signal-cables-Ra228-to-Ac228:
  template: template.mac
  generator: Ra228-to-Ac228
  confinement: hv-signal-cables
  number_of_primaries: 100000000
  number_of_jobs: 1250

l200a-hv-signal-cables-K42:
  template: template.mac
  generator: K42
  confinement: hv-signal-cables
  number_of_primaries: 100000000
  number_of_jobs: 2000

l200a-lar-cylinder-K42:
  template: template.mac
  generator: K42
  confinement: lar-cylinder
  number_of_primaries: 500000000
  number_of_jobs: 500

l200a-lar-inside-ms-K42:
  template: template.mac
  generator: K42
  confinement: lar-inside-ms
  number_of_primaries: 500000000
  number_of_jobs: 500

l200a-lar-outside-ms-K42:
  template: template.mac
  confinement: lar-outside-ms
  generator: K42
  number_of_primaries: 500000000
  number_of_jobs: 500

l200a-lar-cylinder-above-array-K42:
  template: template.mac
  generator: K42
  confinement: lar-cylinder-above-array
  number_of_primaries: 10000000
  number_of_jobs: 250

l200a-lar-hpge-shell-K42:
  template: template.mac
  generator: K42
  confinement: lar-hpge-shell
  number_of_primaries: 100000000
  number_of_jobs: 500

l200a-mini-shroud-surface-K42:
  template: template.mac
  generator: K42
  confinement: mini-shroud-surface
  number_of_primaries: 100000000
  vertices: l200a-mini-shroud-surface-vertices

l200a-mini-shroud-K40:
  template: template.mac
  generator: K40
  confinement: mini-shroud
  number_of_primaries: 100000000
  number_of_jobs: 250

l200a-mini-shroud-Ra224-to-Pb208:
  template: template.mac
  generator: Ra224-to-Pb208
  confinement: mini-shroud
  number_of_primaries: 100000000
  number_of_jobs: 800

l200a-mini-shroud-Rn222-to-Po214:
  template: template.mac
  generator: Rn222-to-Po214
  confinement: mini-shroud
  number_of_primaries: 100000000
  number_of_jobs: 800

l200a-mini-shroud-Ra228-to-Ac228:
  template: template.mac
  generator: Ra228-to-Ac228
  confinement: mini-shroud
  number_of_primaries: 100000000
  number_of_jobs: 400

l200a-calibration-tubes-Ra224-to-Pb208:
  template: template.mac
  generator: Ra224-to-Pb208
  confinement: calibration-tubes
  number_of_primaries: 100000000
  number_of_jobs: 800

l200a-calibration-tubes-Rn222-to-Po214:
  template: template.mac
  generator: Rn222-to-Po214
  confinement: calibration-tubes
  number_of_primaries: 100000000
  number_of_jobs: 800

l200a-pen-plates-K40:
  template: template.mac
  generator: K40
  confinement: pen-plates
  number_of_primaries: 100000000
  number_of_jobs: 250

l200a-pen-plates-Ra224-to-Pb208:
  template: template.mac
  generator: Ra224-to-Pb208
  confinement: pen-plates
  number_of_primaries: 100000000
  number_of_jobs: 640

l200a-pen-plates-Rn222-to-Po214:
  template: template.mac
  generator: Rn222-to-Po214
  confinement: pen-plates
  number_of_primaries: 100000000
  number_of_jobs: 640

l200a-pen-plates-Ra228-to-Ac228:
  template: template.mac
  generator: Ra228-to-Ac228
  confinement: pen-plates
  number_of_primaries: 100000000
  number_of_jobs: 50

l200a-sipm-arrays-K40:
  template: template.mac
  generator: K40
  confinement: sipm-arrays
  number_of_primaries: 100000000
  number_of_jobs: 100

l200a-sipm-arrays-Ra224-to-Pb208:
  template: template.mac
  generator: Ra224-to-Pb208
  confinement: sipm-arrays
  number_of_primaries: 100000000
  number_of_jobs: 1000

l200a-sipm-arrays-Rn222-to-Po214:
  template: template.mac
  generator: Rn222-to-Po214
  confinement: sipm-arrays
  number_of_primaries: 100000000
  number_of_jobs: 1250

l200a-sipm-arrays-Ra228-to-Ac228:
  template: template.mac
  generator: Ra228-to-Ac228
  confinement: sipm-arrays
  number_of_primaries: 100000000
  number_of_jobs: 800

l200a-wls-reflector-K40:
  template: template.mac
  generator: K40
  confinement: wls-reflector
  number_of_primaries: 1000000000
  number_of_jobs: 500

l200a-wls-reflector-Ra224-to-Pb208:
  template: template.mac
  generator: Ra224-to-Pb208
  confinement: wls-reflector
  number_of_primaries: 1000000000
  number_of_jobs: 1000

l200a-wls-reflector-Rn222-to-Po214:
  template: template.mac
  generator: Rn222-to-Po214
  confinement: wls-reflector
  number_of_primaries: 1000000000
  number_of_jobs: 1000

l200a-wls-reflector-Ra228-to-Ac228:
  template: template.mac
  generator: Ra228-to-Ac228
  confinement: wls-reflector
  number_of_primaries: 1000000000
  number_of_jobs: 1000

l200a-lar-cylinder-Ar39:
  template: template.mac
  generator: Ar39
  confinement: lar-cylinder
  number_of_primaries: 5000000000
  number_of_jobs: 2500
