scintillator_volume_name: liquid_argon
optmap_per_sipm: true

# these values are not tuned to a particular value
max_pes_per_hit_per_sipm: 5
max_pes_per_hit_combined: 100

# the maps are produced with SiPM PDE = 1
# here we restore the correct PDE normalization
map_scaling: 0.3

# these numbers are a guess
photoelectron_res: 0.3
time_resolution_ns: 16

# this needs to be on the low side since there can be many LAr energy
# depositions in some events (e.g. Tl208)
buffer_len: 10*MB
