/MG/manager/mglog routine
/MG/manager/seedWithUUID

/MG/processes/useNoHadPhysics true

/MG/geometry/detector LGND_200_Baseline
/MG/geometry/WorldMaterial Vacuum
/MG/L200/MakeSiPlatePEN true

/MG/eventaction/reportingfrequency 1000
/MG/eventaction/rootschema GSS
/MG/eventaction/rootfilename $OUTPUT_FILE

/run/initialize

/MG/generator/select GSS
/MG/io/gss/addVolume DetectorArray_001_StringAssembly_001_MiniShroudNylon_001
/MG/io/gss/addVolume DetectorArray_001_StringAssembly_002_MiniShroudNylon_001
/MG/io/gss/addVolume DetectorArray_001_StringAssembly_003_MiniShroudNylon_001
/MG/io/gss/addVolume DetectorArray_001_StringAssembly_004_MiniShroudNylon_001
/MG/io/gss/addVolume DetectorArray_001_StringAssembly_005_MiniShroudNylon_001
/MG/io/gss/addVolume DetectorArray_001_StringAssembly_007_MiniShroudNylon_001
/MG/io/gss/addVolume DetectorArray_001_StringAssembly_008_MiniShroudNylon_001
/MG/io/gss/addVolume DetectorArray_001_StringAssembly_009_MiniShroudNylon_001
/MG/io/gss/addVolume DetectorArray_001_StringAssembly_010_MiniShroudNylon_001
/MG/io/gss/addVolume DetectorArray_001_StringAssembly_011_MiniShroudNylon_001

/MG/generator/gss/origin 0 0 0 m
/MG/generator/gss/boundingR 0.6 m
/MG/io/gss/setMaxIntersections 16 # can intersect up to 4 strings

/run/beamOn $NUMBER_OF_PRIMARIES
